### ISSUE TITLE
Can not wait to see the open-source code

### ISSUE THREAD

**Issue by mo666666** [stanislavfort/ensemble-everything-everywhere#1]
Hi, Stanislav Fort! Thank you for your interesting and solid work! Can not wait to see the release of open-source code, as it would greatly enhance our understanding and application of your research.

Look forward to your reply.

**Comment by stanislavfort** [comment]
The code for the key experiments is in this Colab: https://github.com/stanislavfort/ensemble-everything-everywhere/blob/main/quick_replication_for_multi_resolution_self_ensemble.ipynb It is a stand-alone training of a multi-resolution self-ensemble on CIFAR-100 and testing on using the RobustBench AutoAttack. It gets >60% adversarial accuracy after L_infty = 8/255 attacks on the first 32 test set images. I'm also visualizing the successful attacks, and directly optimizing from grey pixels towards all 100 CIFAR-100 classes and the resulting interpretable images of the semantic content of the class (not noise, as usual for brittle models).
